/*
 * File: app/view/AccountListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.AccountListContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Action'
    ],

    itemId: 'accountListContainer',
    padding: 5,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnAdd',
                            margin: 5,
                            text: 'Add Account'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    frame: true,
                    itemId: 'accountListGrid',
                    margin: '5 0 0 0',
                    title: 'Account List',
                    columnLines: true,
                    store: 'AccountListStore',
                    viewConfig: {
                        frame: false,
                        itemId: 'accountListGridView'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            draggable: false,
                            frame: false,
                            dataIndex: 'id',
                            menuDisabled: true,
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            draggable: false,
                            width: 150,
                            dataIndex: 'username',
                            menuDisabled: true,
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            draggable: false,
                            width: 300,
                            dataIndex: 'permission',
                            menuDisabled: true,
                            text: 'Permission'
                        },
                        {
                            xtype: 'actioncolumn',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var p = Ext.create('digitalmenu.view.AddUpdateAccountForm',{
                                            title: 'Update User'
                                        });

                                        //hide one save button & password components
                                        p.down('#btnSaveForAdd').hidden = true;
                                        p.down('#btnSaveForUpdate').hidden = false;
                                        p.down('#passwordTxt').hidden = true;
                                        p.down('#passwordAgainTxt').hidden = true;

                                        //set data
                                        p.down('#usernameTxt').setValue(record.data.username);
                                        p.down('#id').setValue(record.data.id);

                                        var permissionGrid = p.down('#permissionGrid');
                                        permissionGrid.store.load(function(records, operation, success){
                                            var permissions = record.data.permission.split(";");
                                            for(var i = 0; i<permissions.length; i++){
                                                var permission = permissions[i];
                                                for (var j =0; j<permissionGrid.store.getCount(); j++){
                                                    if (permission === permissionGrid.store.getAt(j).get('name')){
                                                        permissionGrid.store.getAt(j).set('choosed', true);
                                                    }
                                                }
                                            }
                                        });

                                        //open panel in a window
                                        var win = Ext.create('Ext.window.Window',{
                                            height: 550,
                                            width: 460,
                                            header: false,
                                            modal: true,
                                            border: false,
                                            items:[
                                            p
                                            ]
                                        });

                                        win.show();
                                    },
                                    icon: 'images/icon_updateuser.png',
                                    tooltip: 'update user'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var p = Ext.create('digitalmenu.view.ChangeUserPasswordForm',{
                                            title: 'Change Password'
                                        });

                                        //set data
                                        p.down('#nfAccountId').setValue(record.data.id);


                                        //open panel in a window
                                        var win = Ext.create('Ext.window.Window',{
                                            header: false,
                                            modal: true,
                                            border: false,
                                            items:[
                                            p
                                            ]
                                        });

                                        win.show();
                                    },
                                    icon: 'images/icon_change_password.png',
                                    tooltip: 'change password'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        Ext.MessageBox.confirm(
                                        "确认",
                                        "您确认要删除账号“" + record.data.username + "”吗？",
                                        function(btnId) {
                                            if (btnId != 'yes')
                                            return;

                                            var values = {
                                                userId: Ext.util.Cookies.get("userId"),
                                                sessionId: Ext.util.Cookies.get("sessionId"),
                                                id: record.data.id
                                            };

                                            var successCallback = function(resp, ops) {
                                                var result = Ext.decode(resp.responseText);

                                                if (result.result == 'ok') {
                                                    Ext.Msg.alert("删除账号成功", result.result);
                                                    view.store.load();
                                                } else if (result.result == 'invalid_session') {
                                                    digitalmenu.getApplication().onSessionExpired();
                                                } else {
                                                    Ext.Msg.alert("删除账号失败", result.result);
                                                }
                                            };

                                            var failureCallback = function(resp, ops) {
                                                Ext.Msg.alert("删除账号失败", resp);
                                            };

                                            Ext.Ajax.request({
                                                url: "account/remove",
                                                params: values,
                                                success: successCallback,
                                                failure: failureCallback
                                            });
                                        });
                                    },
                                    icon: 'images/icon_delete.png',
                                    tooltip: 'delete user'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});