/*
 * File: app/view/AddIndentDishForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.AddIndentDishForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 220,
    itemId: 'formAddIndentDish',
    width: 347,
    bodyPadding: 10,
    title: 'Add Dish',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    hidden: true,
                    itemId: 'nfIndentId',
                    fieldLabel: 'id',
                    name: 'indentId'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cbCategory1',
                    fieldLabel: 'Category1',
                    editable: false,
                    displayField: 'chineseName',
                    store: 'Category1Store',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cbCategory2',
                    fieldLabel: 'Category2',
                    editable: false,
                    displayField: 'chineseName',
                    store: 'Category2Store',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cbDish',
                    fieldLabel: 'Dish',
                    name: 'dishId',
                    allowBlank: false,
                    editable: false,
                    displayField: 'chineseName',
                    forceSelection: true,
                    store: 'DishStore',
                    valueField: 'id'
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    itemId: 'nfAmount',
                    fieldLabel: 'Amount',
                    name: 'amount',
                    allowBlank: false,
                    maxValue: 2000,
                    minValue: 1
                },
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'btnSave',
                    margin: 5,
                    width: 100,
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.MessageBox.confirm(
                        "Confirm",
                        "Will you give up all the data input in this form?",
                        function(btnId){
                            if (btnId == 'no')
                            return;
                            var win = button.up('form').up('window');
                            win.close();
                        }
                        );

                    },
                    itemId: 'btnCancel',
                    margin: 5,
                    width: 100,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});