/*
 * File: app/view/AddUpdateAccountForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.AddUpdateAccountForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.grid.column.CheckColumn',
        'Ext.button.Button'
    ],

    frame: true,
    height: 526,
    itemId: 'addUpdateAccountForm',
    margin: 5,
    width: 438,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'usernameTxt',
                            width: 400,
                            fieldLabel: 'User Name',
                            labelWidth: 150,
                            name: 'username',
                            maxLength: 32,
                            minLength: 4
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'passwordTxt',
                            width: 400,
                            fieldLabel: 'Password',
                            labelWidth: 150,
                            name: 'password',
                            inputType: 'password',
                            maxLength: 64,
                            minLength: 4
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'passwordAgainTxt',
                            width: 400,
                            fieldLabel: 'Confirm Password',
                            labelWidth: 150,
                            name: 'passwordAgain',
                            inputType: 'password',
                            maxLength: 64,
                            minLength: 4
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            itemId: 'id',
                            fieldLabel: 'Label',
                            name: 'id'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    height: 300,
                    itemId: 'permissionGrid',
                    width: 300,
                    title: 'Permission',
                    hideHeaders: true,
                    store: 'PermissionStore',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'id'
                        },
                        {
                            xtype: 'checkcolumn',
                            width: 50,
                            dataIndex: 'choosed'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 250,
                            dataIndex: 'name'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnSaveForAdd',
                            margin: 5,
                            width: 120,
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSaveForUpdate',
                            margin: 5,
                            width: 120,
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancel',
                            margin: 5,
                            width: 120,
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});