/*
 * File: app/view/ChangeDishPictureForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.ChangeDishPictureForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    height: 126,
    itemId: 'formChangeDishPicture',
    width: 453,
    bodyPadding: 10,
    title: 'Change Dish Price',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    hidden: true,
                    itemId: 'nfId',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'filefield',
                    anchor: '100%',
                    fieldLabel: 'Picture',
                    name: 'picture',
                    allowBlank: false
                },
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'btnSave',
                    margin: 5,
                    width: 100,
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var win = button.up('form').up('window');
                        win.close();
                    },
                    itemId: 'btnCancel',
                    margin: 5,
                    width: 100,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});