/*
 * File: app/view/ChangeUserPasswordForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.ChangeUserPasswordForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 191,
    itemId: 'formChangeUserPassord',
    width: 285,
    bodyPadding: 10,
    title: 'Change Password',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    hidden: true,
                    itemId: 'nfAccountId',
                    fieldLabel: 'Label',
                    name: 'accountId'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    formBind: false,
                    itemId: 'txtOldPassword',
                    fieldLabel: 'Old Password',
                    labelWidth: 150,
                    name: 'oldPassword',
                    minLength: 4
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    formBind: false,
                    itemId: 'txtNewPassword',
                    fieldLabel: 'New Password',
                    labelWidth: 150,
                    name: 'newPassword',
                    minLength: 4
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    formBind: false,
                    itemId: 'txtReNewPassword',
                    fieldLabel: 'Re New Password',
                    labelWidth: 150,
                    name: 'reNewPassword',
                    minLength: 4
                },
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'btnSave',
                    margin: 5,
                    width: 100,
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.MessageBox.confirm(
                        "Confirm",
                        "Will you give up all the data input in this form?",
                        function(btnId){
                            if (btnId == 'no')
                            return;
                            var win = button.up('form').up('window');
                            win.close();
                        }
                        );

                    },
                    itemId: 'btnCancel',
                    margin: 5,
                    width: 100,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});