/*
 * File: app/view/ChangeConfirmCodeForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.ChangeConfirmCodeForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    height: 143,
    itemId: 'formChangeConfirmCode',
    width: 269,
    bodyPadding: 10,
    title: 'Change Confirm Code',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    disabled: true,
                    itemId: 'tfOldCode',
                    fieldLabel: 'Old Code',
                    submitValue: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'tfNewCode',
                    fieldLabel: 'New Code',
                    name: 'code'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var successCallback = function(form, action){
                            var result = action.result;

                            if(action.result.result =='ok'){
                                Ext.Msg.alert("SUCCESS","Change Confirm Code Successfully.");
                                var win = button.up('form').up('window');
                                win.close();
                            } else if (action.result.result == 'invalid_session'){
                                digitalmenu.getApplication().onSessionExpired();
                            } else {
                                Ext.Msg.alert('Failed', 'failed to change confirm code, please do again');
                            }
                        };

                        var failureCallback = function(form, action){
                            Ext.Msg.alert('Failed','failed to change confirm code, please do again');
                        };
                        button.up('form').submit({
                            url: 'common/saveconfirmcode',
                            params: {
                                userId : Ext.util.Cookies.get('userId'),
                                sessionId : Ext.util.Cookies.get('sessionId')
                            },
                            success : successCallback,
                            failure : failureCallback
                        });
                    },
                    itemId: 'btnSave',
                    margin: 5,
                    width: 100,
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {

                        var win = button.up('form').up('window');
                        win.close();

                    },
                    itemId: 'btnCancel',
                    margin: 5,
                    width: 100,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});