/*
 * File: app/view/DeskManageContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.DeskManageContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    height: 652,
    itemId: 'deskManageContainer',
    width: 946,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    getSelectDesks: function(desklist) {
                        var arrSelected = [];
                        desklist.forEach(function(element, index, array){
                            if (element.isSelected){
                                arrSelected.push(element);
                            }
                        });
                        return arrSelected;
                    },
                    desklist: [
                        
                    ],
                    region: 'center',
                    itemId: 'pDeskArea',
                    layout: {
                        type: 'table',
                        columns: 5
                    }
                },
                {
                    xtype: 'panel',
                    region: 'east',
                    itemId: 'pFunction',
                    width: 150,
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'btnCheckout',
                            margin: '10 0 10 10',
                            width: 130,
                            text: '收银'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            height: 40,
                            itemId: 'btnMergeDesk',
                            margin: '10 0 10 10',
                            width: 130,
                            text: '拼桌'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            margin: '10 0 0 10',
                            width: 130,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            margin: '10 0 0 10',
                            width: 130,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            margin: '10 0 0 10',
                            width: 130,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            margin: '10 0 0 10',
                            width: 130,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            margin: '10 0 0 10',
                            width: 130,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'btnPrintDuizhangdan',
                            margin: '10 0 10 10',
                            width: 130,
                            text: '打印对账单'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            height: 40,
                            itemId: 'btnAddDish',
                            margin: '10 0 10 10',
                            width: 130,
                            text: '加单'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            height: 40,
                            itemId: 'btnRefresh',
                            margin: '10 0 0 10',
                            width: 130,
                            text: '刷新'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});