/*
 * File: app/view/DeskCell.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.DeskCell', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.deskCellPanel',

    requires: [
        'Ext.form.Label'
    ],

    isSelected: false,
    border: 5,
    height: 150,
    margin: '5 0 0 5',
    width: 150,
    overflowX: 'auto',
    overflowY: 'auto',
    bodyBorder: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            bodyStyle: {
                borderColor: 'red',
                borderStyle: 'solid'
            },
            items: [
                {
                    xtype: 'label',
                    cls: 'desknolabel',
                    itemId: 'lbDeskNo'
                },
                {
                    xtype: 'label',
                    itemId: 'lbCustomerAmount',
                    margin: '10 0 0 0'
                },
                {
                    xtype: 'label',
                    itemId: 'lbPrice',
                    margin: '10 0 0 0'
                },
                {
                    xtype: 'label',
                    itemId: 'lbStartTime',
                    margin: '10 0 0 0'
                }
            ]
        });

        me.callParent(arguments);
    }

});