/*
 * File: app/view/IndentCheckoutForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.IndentCheckoutForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    frame: true,
    height: 512,
    itemId: 'indentCheckoutForm',
    margin: 5,
    width: 624,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            margins: '',
                            cls: 'font40bold',
                            height: 40,
                            itemId: 'lbDeskNo',
                            margin: '20 0 0 0',
                            text: 'My Label'
                        },
                        {
                            xtype: 'label',
                            cls: 'font40bold',
                            height: 40,
                            itemId: 'lbIndentPrice',
                            margin: '20 0 0 0',
                            text: 'My Label'
                        },
                        {
                            xtype: 'radiogroup',
                            flex: 1,
                            margin: '20 0 0 0',
                            width: 400,
                            fieldLabel: 'Pay Method',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rbPayByCash',
                                    name: 'pay',
                                    boxLabel: 'Cash',
                                    checked: true
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rbPayByCard',
                                    name: 'pay',
                                    boxLabel: 'Bank Card'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rbPayByMember',
                                    name: 'pay',
                                    boxLabel: 'Memeber Card'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: '20 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    width: 230,
                                    items: [
                                        {
                                            xtype: 'radiogroup',
                                            width: 260,
                                            fieldLabel: 'Discount',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rbNonDiscount',
                                                    name: 'discount',
                                                    boxLabel: 'No Discount',
                                                    checked: true
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    disabled: true,
                                                    itemId: 'rbDiscountTemplate',
                                                    margin: '15 0 0 0',
                                                    name: 'discount',
                                                    boxLabel: 'Template'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    itemId: 'rbDirectDiscount',
                                                    margin: '15 0 0 0',
                                                    name: 'discount',
                                                    boxLabel: 'Direct'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    width: 320,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'cbDiscountTemplate',
                                            margin: '45 0 0 0',
                                            fieldLabel: 'Template'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'nfDirectDiscount',
                                            margin: '15 0 0 0',
                                            fieldLabel: 'Discount'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: '20 0 0 0',
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'font40bold',
                                    height: 40,
                                    itemId: 'lbDiscountPrice1',
                                    margin: '20 0 0 0',
                                    text: 'After Discount Price : $'
                                },
                                {
                                    xtype: 'label',
                                    cls: 'font40bold',
                                    height: 40,
                                    itemId: 'lbDiscountPrice',
                                    margin: '20 0 0 0'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margin: '20 0 0 0',
                    items: [
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'btnPay',
                            margin: 5,
                            width: 120,
                            text: 'Pay'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.Msg.confirm("Confirm", "Will you cancel the payment of this order?",
                                function(btnId){
                                    if (btnId === 'no'){
                                        return;
                                    }
                                    button.up('window').close();
                                });

                            },
                            height: 40,
                            itemId: 'btnCancel',
                            margin: '5 5 5 80',
                            width: 120,
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});