/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.LoginView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    itemId: 'loginView',

    layout: {
        type: 'hbox',
        align: 'middle',
        pack: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    draggable: true,
                    frame: true,
                    height: 200,
                    itemId: 'loginForm',
                    width: 300,
                    bodyPadding: 10,
                    title: 'Login - Digital Menu',
                    items: [
                        {
                            xtype: 'container',
                            height: 20
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'usernameText',
                            fieldLabel: 'User Name ',
                            name: 'username',
                            value: 'admin',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            maxLength: 32,
                            minLength: 4
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'passwordText',
                            fieldLabel: 'Password ',
                            name: 'password',
                            value: 'admin',
                            inputType: 'password',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            enableKeyEvents: true,
                            maxLength: 16,
                            minLength: 4
                        },
                        {
                            xtype: 'container',
                            height: 65,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    height: 30,
                                    itemId: 'loginBtn',
                                    width: 100,
                                    text: 'LOGIN'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});