/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: 'border',
                    bodyBorder: true,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnAccount',
                                    width: 150,
                                    icon: 'images/icon_users.png',
                                    text: 'Account'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMaintain',
                                    width: 150,
                                    icon: 'images/icon_maintain2.png',
                                    text: 'Maintain Tools',
                                    menu: {
                                        xtype: 'menu',
                                        minWidth: 200,
                                        width: 200,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuitem_maintain_confirmcode',
                                                text: 'Change Confirm Code'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuitem_maintain_menu',
                                                icon: 'images/icon_maintain_menu.png',
                                                text: 'Maintain Menu'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuitem_maintain_desk',
                                                icon: 'images/icon_maintain_table.png',
                                                text: 'Maintain Desk'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuitem_maintain_printer',
                                                icon: 'images/icon_maintain_printer.png',
                                                text: 'Maintain Printer'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'menuitem_maintain_discounttemplate',
                                                text: 'Maintain Discount Template'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnIndent',
                                    width: 150,
                                    text: 'Order'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnTableMgr',
                                    width: 150,
                                    text: 'TableMgr'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnQuery',
                                    width: 150,
                                    icon: 'images/icon_query.png',
                                    text: 'Query',
                                    menu: {
                                        xtype: 'menu',
                                        minWidth: 200,
                                        width: 200,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'logQueryMenuItem',
                                                text: 'Query Log'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'indentQueryMenuItem',
                                                text: 'Query Order'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'shiftWorkQueryMenuItem',
                                                text: 'Query ShiftWork'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            itemId: 'contentPanel',
                            autoScroll: true,
                            layout: 'border',
                            bodyBorder: false
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});