/*
 * File: app/view/MenuContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.MenuContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.form.field.File',
        'Ext.Img'
    ],

    itemId: 'menuContainer',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    minWidth: 100,
                    padding: 5,
                    width: 300,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'treepanel',
                            region: 'center',
                            itemId: 'treeMenu',
                            margin: 5,
                            store: 'MenuTreeStore',
                            displayField: 'displayText',
                            viewConfig: {
                                width: 200
                            },
                            listeners: {
                                itemcontextmenu: {
                                    fn: me.onTreeMenuItemContextMenu,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            region: 'south',
                            height: 40,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '5',
                                    itemId: 'btnAdd',
                                    width: 80,
                                    text: 'ADD'
                                },
                                {
                                    xtype: 'button',
                                    margins: '5',
                                    itemId: 'btnModify',
                                    width: 80,
                                    text: 'MODIFY'
                                },
                                {
                                    xtype: 'button',
                                    margins: '5',
                                    itemId: 'btnDelete',
                                    width: 80,
                                    text: 'DELETE'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'tabCategory1',
                                    padding: 5,
                                    layout: 'border',
                                    title: 'Category 1',
                                    items: [
                                        {
                                            xtype: 'form',
                                            region: 'center',
                                            bodyPadding: 10,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'tfCategory1CN',
                                                    width: 400,
                                                    fieldLabel: 'Chinese Name',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    maxLength: 32,
                                                    minLength: 1
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'tfCategory1EN',
                                                    width: 400,
                                                    fieldLabel: 'English Name',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    maxLength: 32,
                                                    minLength: 1
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'nfCategory1Seq',
                                                    width: 400,
                                                    fieldLabel: 'Display Sequence',
                                                    labelWidth: 150,
                                                    value: 1,
                                                    allowBlank: false,
                                                    maxValue: 100,
                                                    minValue: 1
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    hidden: true,
                                                    itemId: 'nfID',
                                                    fieldLabel: 'ID',
                                                    value: 0
                                                },
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    hidden: true,
                                                    itemId: 'btnSaveNewCategory1',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'CREATE'
                                                },
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    hidden: true,
                                                    itemId: 'btnSaveOldCategory1',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'UPDATE'
                                                },
                                                {
                                                    xtype: 'button',
                                                    hidden: true,
                                                    itemId: 'btnCancel',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'CANCEL'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    itemId: 'tabCategory2',
                                    padding: 5,
                                    layout: 'border',
                                    title: 'Category 2',
                                    items: [
                                        {
                                            xtype: 'form',
                                            region: 'center',
                                            bodyPadding: 10,
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'tfCategory2CN',
                                                    width: 400,
                                                    fieldLabel: 'Chinese Name',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    maxLength: 32,
                                                    minLength: 1
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'tfCategory2EN',
                                                    width: 400,
                                                    fieldLabel: 'English Name',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    maxLength: 32,
                                                    minLength: 1
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'nfCategory2Seq',
                                                    width: 400,
                                                    fieldLabel: 'Display Sequence',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    maxValue: 100,
                                                    minValue: 1
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cbCategory1ID',
                                                    width: 400,
                                                    fieldLabel: 'Category1',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    editable: false,
                                                    displayField: 'chineseName',
                                                    forceSelection: true,
                                                    queryMode: 'local',
                                                    store: 'Category1Store',
                                                    valueField: 'id'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cbPrinter',
                                                    width: 400,
                                                    fieldLabel: 'Printer',
                                                    labelWidth: 150,
                                                    allowBlank: false,
                                                    allowOnlyWhitespace: false,
                                                    editable: false,
                                                    displayField: 'name',
                                                    forceSelection: true,
                                                    store: 'PrinterListStore',
                                                    valueField: 'id'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    hidden: true,
                                                    itemId: 'nfID',
                                                    fieldLabel: 'ID',
                                                    value: 0
                                                },
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    hidden: true,
                                                    itemId: 'btnSaveNewCategory2',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'CREATE'
                                                },
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    hidden: true,
                                                    itemId: 'btnSaveOldCategory2',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'UPDATE'
                                                },
                                                {
                                                    xtype: 'button',
                                                    hidden: true,
                                                    itemId: 'btnCancel',
                                                    margin: 5,
                                                    width: 100,
                                                    text: 'CANCEL'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: 500,
                                    itemId: 'tabDish',
                                    padding: 5,
                                    layout: 'border',
                                    manageHeight: false,
                                    title: 'Dish',
                                    items: [
                                        {
                                            xtype: 'form',
                                            region: 'center',
                                            layout: 'border',
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    region: 'north',
                                                    height: 150,
                                                    layout: {
                                                        type: 'table',
                                                        columns: 2
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            hidden: true,
                                                            itemId: 'nfID',
                                                            fieldLabel: 'ID',
                                                            name: 'id',
                                                            value: 0
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'tfDishCN',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Chinese Name',
                                                            labelWidth: 150,
                                                            name: 'chineseName',
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            maxLength: 32,
                                                            minLength: 1
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'tfDishEN',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'English Name',
                                                            labelWidth: 150,
                                                            name: 'englishName',
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            maxLength: 32,
                                                            minLength: 4
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'nfDishSeq',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Display Sequence',
                                                            labelWidth: 150,
                                                            name: 'sequence',
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            maxValue: 100,
                                                            minValue: 1
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            itemId: 'nfPrice',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Price',
                                                            labelWidth: 150,
                                                            name: 'price',
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            maxValue: 1000,
                                                            minValue: 0
                                                        },
                                                        {
                                                            xtype: 'checkboxgroup',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    itemId: 'cbSpecial',
                                                                    name: 'isSpecial',
                                                                    boxLabel: 'Special'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    itemId: 'cbNew',
                                                                    name: 'isNew',
                                                                    boxLabel: 'New'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            itemId: 'cbHotLevel',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Hot Level',
                                                            labelWidth: 150,
                                                            name: 'hotLevel',
                                                            editable: false,
                                                            displayField: 'name',
                                                            forceSelection: true,
                                                            queryMode: 'local',
                                                            store: 'HotLevelLocalStore',
                                                            valueField: 'id'
                                                        },
                                                        {
                                                            xtype: 'combobox',
                                                            itemId: 'cbCategory2ID',
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Category2',
                                                            labelWidth: 150,
                                                            name: 'category2Id',
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            editable: false,
                                                            displayField: 'chineseName',
                                                            forceSelection: true,
                                                            queryMode: 'local',
                                                            store: 'Category2Store',
                                                            valueField: 'id'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    region: 'center',
                                                    items: [
                                                        {
                                                            xtype: 'filefield',
                                                            height: 30,
                                                            itemId: 'dishPicture',
                                                            maxWidth: 400,
                                                            minWidth: 400,
                                                            padding: 5,
                                                            width: 400,
                                                            fieldLabel: 'Picture',
                                                            labelWidth: 150,
                                                            name: 'dishPicture'
                                                        },
                                                        {
                                                            xtype: 'image',
                                                            height: 520,
                                                            itemId: 'image',
                                                            width: 710
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    region: 'south',
                                                    height: 40,
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            formBind: true,
                                                            hidden: true,
                                                            itemId: 'btnSaveNewDish',
                                                            margin: 5,
                                                            width: 100,
                                                            text: 'CREATE'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            formBind: true,
                                                            hidden: true,
                                                            itemId: 'btnSaveOldDish',
                                                            margin: 5,
                                                            width: 100,
                                                            text: 'UPDATE'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            hidden: true,
                                                            itemId: 'btnCancel',
                                                            margin: 5,
                                                            width: 100,
                                                            text: 'CANCEL'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTreeMenuItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        e.stopEvent();
        var menuContainer = dataview.up('#menuContainer');
        if (record.get('level') == 'DISH'){
            var popMenu = Ext.create('Ext.menu.Menu', {
                items:[{
                    text: record.get('isSpecial') === true ? 'Cancel Special' : 'Set Special',
                    itemId: 'menuitem_setSpecial',
                    handler: function(){
                        menuContainer.setDishSpecial(record);
                    }
                }, {
                    text: record.get('isNew') === true ? 'Cancel New Dish' : 'Set New Dish',
                    itemId: 'menuitem_setNewDish',
                    handler: function(){
                        menuContainer.setNewProduct(record);
                    }
                }, {
                    text: 'Change Picture',
                    itemId: 'menuitem_changePicture',
                    handler: function(){
                        menuContainer.changeDishPicture(record);
                    }
                }, {
                    text: 'Change Price',
                    itemId: 'menuitem_changePrice',
                    handler: function(){
                        menuContainer.changeDishPrice(record);
                    }
                }, {
                    text: record.get('isSoldOut') === true ? 'Cancel Sold Out' : 'Set Sold Out',
                    itemId: 'menuitem_setsoldout',
                    handler: function(){
                        menuContainer.setSoldOut(record);
                    }
                }]
            });
            popMenu.showAt(e.getXY());
        } else if (record.get('level') == 'C1'){

        } else if (record.get('level') == 'C2'){

        }


    },

    setDishSpecial: function(record) {


        var values = {
            userId : Ext.util.Cookies.get('userId'),
            sessionId : Ext.util.Cookies.get('sessionId'),
            id : record.get('objectid'),
            isSpecial : !record.get('isSpecial')
        };

        var successCallback = function(resp, opts){
            var result = Ext.decode(resp.responseText);
            if (result.result == 'ok'){
                record.set('isSpecial', !record.get('isSpecial'));
                if (record.get('isSpecial')){
                    record.set('displayText', record.get('displayText') + "<html><font color=red>[SPECIAL]</font></html>");
                } else {
                    record.set('displayText', record.get('displayText').replace("[SPECIAL]",""));
                }


                Ext.Msg.alert("SUCCESS","Done successfully.");
            } else if (result.result == 'invalid_session'){
                digitalmenu.getApplication().onSessionExpired();
            } else {
                Ext.Msg.alert('failed to do, please do again');
            }
        };

        var failureCallback = function(resp, opts){
            Ext.Msg.alert('failed to do, please do again');
        };

        var confirmmsg = "Do you want to set " + record.get('chineseName') + " Special?";
        if (record.get('isSpecial')){
            confirmmsg = "Do you want to cancel Special of " + record.get('chineseName') + "?";
        }
        Ext.Msg.confirm("Confirm", confirmmsg,
                        function(btnId){
                            if (btnId === 'no'){
                                return;
                            }
                            Ext.Ajax.request({
                                url: "menu/change_dish_special",
                                params : values,
                                success : successCallback,
                                failure : failureCallback
                            });
                        });
    },

    setNewProduct: function(record) {
        var values = {
            userId : Ext.util.Cookies.get('userId'),
            sessionId : Ext.util.Cookies.get('sessionId'),
            id : record.get('objectid'),
            isNew : !record.get('isNew')
        };

        var successCallback = function(resp, opts){
            var result = Ext.decode(resp.responseText);
            if (result.result === 'ok'){
                record.set('isNew', !record.get('isNew'));

                if (record.get('isNew')){
                    record.set('displayText', record.get('displayText') + "<html><font color=red>[NEW]</font></html>");
                } else {
                    record.set('displayText', record.get('displayText').replace("[NEW]",""));
                }


                Ext.Msg.alert("SUCCESS","Done successfully.");
            } else if (result.result === 'invalid_session'){
                digitalmenu.getApplication().onSessionExpired();
            } else {
                Ext.Msg.alert('failed to do, please do again');
            }
        };

        var failureCallback = function(resp, opts){
            Ext.Msg.alert('failed to do, please do again');
        };

        var confirmmsg = "Do you want to set " + record.get('chineseName') + " New Dish?";
        if (record.get('isNew')){
            confirmmsg = "Do you want to cancel New Dish of " + record.get('chineseName') + "?";
        }

        Ext.Msg.confirm("Confirm", confirmmsg,
                        function(btnId){
                            if (btnId === 'no'){
                                return;
                            }
                            Ext.Ajax.request({
                                url: "menu/change_dish_newproduct",
                                params : values,
                                success : successCallback,
                                failure : failureCallback
                            });
                        });
    },

    changeDishPrice: function(record) {
        var p = Ext.create('digitalmenu.view.ChangeDishPriceForm');

        p.down('#nfOldPrice').setValue(record.get('price'));
        p.down('#nfId').setValue(record.get('objectid'));

        var win = Ext.create('Ext.window.Window',{

            height: 153,
            width: 280,
        	header: false,
        	modal: true,
            border: false,
        	items:[ p ]
        });

        win.show();
    },

    changeDishPicture: function(record) {
        var p = Ext.create('digitalmenu.view.ChangeDishPictureForm');

        p.down('#nfId').setValue(record.get('objectid'));

        var win = Ext.create('Ext.window.Window',{
        	header: false,
        	modal: true,
            border: false,
        	items:[ p ]
        });

        win.show();
    },

    setSoldOut: function(record) {
        var values = {
            userId : Ext.util.Cookies.get('userId'),
            sessionId : Ext.util.Cookies.get('sessionId'),
            id : record.get('objectid'),
            isSoldOut : !record.get('isSoldOut')
        };

        var successCallback = function(resp, opts){
            var result = Ext.decode(resp.responseText);
            if (result.result === 'ok'){
                record.set('isSoldOut', !record.get('isSoldOut'));

                if (record.get('isSoldOut')){
                    record.set('displayText', record.get('displayText') + "<html><font color=blue>[SOLDOUT]</font></html>");
                } else {
                    record.set('displayText', record.get('displayText').replace("[SOLDOUT]",""));
                }

                Ext.Msg.alert("SUCCESS","Done successfully.");
            } else if (result.result === 'invalid_session'){
                digitalmenu.getApplication().onSessionExpired();
            } else {
                Ext.Msg.alert('failed to do, please do again');
            }
        };


        var failureCallback = function(resp, opts){
            Ext.Msg.alert('failed to do, please do again');
        };

        var confirmmsg = "Do you want to set " + record.get('chineseName') + " as SOLD OUT?";
        if (record.get('isSoldOut')){
            confirmmsg = "Do you want to cancel dish " + record.get('chineseName') + " as SOLD OUT?";
        }

        Ext.Msg.confirm("Confirm", confirmmsg,
                        function(btnId){
                            if (btnId === 'no'){
                                return;
                            }
                            Ext.Ajax.request({
                                url: "menu/changedishsoldout",
                                params : values,
                                success : successCallback,
                                failure : failureCallback
                            });
                        });
    }

});