/*
 * File: app/view/ShiftWorkListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.view.ShiftWorkListContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    height: 466,
    itemId: 'shiftWorkContainer',
    padding: 5,
    width: 843,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 58,
                    itemId: 'queryForm',
                    margin: 5,
                    layout: 'column',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'datefield',
                            itemId: 'startTime',
                            fieldLabel: 'Start Time',
                            name: 'startTime'
                        },
                        {
                            xtype: 'datefield',
                            itemId: 'endTime',
                            fieldLabel: 'End Time',
                            name: 'endTime'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtUsername',
                            fieldLabel: 'User',
                            name: 'username'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = button.up('form');
                                grid = form.up('container').down('grid');
                                values = form.getValues();

                                grid.store.proxy.extraParams.userId = Ext.util.Cookies.get('userId');
                                grid.store.proxy.extraParams.sessionId = Ext.util.Cookies.get('sessionId');
                                grid.store.proxy.extraParams.username = values.username;
                                grid.store.proxy.extraParams.beginTime = values.startTime;
                                grid.store.proxy.extraParams.endTime = values.endTime;

                                grid.store.load();
                            },
                            formBind: true,
                            itemId: 'btnQuery',
                            text: 'Query'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    itemId: 'shiftWorkListGrid',
                    margin: 5,
                    columnLines: true,
                    store: 'ShiftWorkListStore',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            itemId: 'id',
                            width: 80,
                            dataIndex: 'id',
                            text: 'ID',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            itemId: 'username',
                            dataIndex: 'userName',
                            text: 'User'
                        },
                        {
                            xtype: 'datecolumn',
                            itemId: 'startTime',
                            width: 150,
                            defaultWidth: 150,
                            dataIndex: 'startTime',
                            text: 'Start Time',
                            format: 'y/M/d H:i:s'
                        },
                        {
                            xtype: 'datecolumn',
                            itemId: 'endTime',
                            width: 150,
                            defaultWidth: 150,
                            dataIndex: 'endTime',
                            text: 'End Time',
                            format: 'y/M/d H:i:s'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'LogListStore'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 50,
                    itemId: 'functionPanel',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnPrintShift',
                            margin: '10 0 0 10',
                            text: '打印交班单'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});