/*
 * File: app/store/DishStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.store.DishStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field',
        'Ext.util.Sorter',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DishStore',
            fields: [
                {
                    name: 'id',
                    type: 'string'
                },
                {
                    name: 'chineseName',
                    type: 'string'
                },
                {
                    name: 'category2Id',
                    type: 'string'
                },
                {
                    name: 'sequence',
                    type: 'int'
                }
            ],
            sorters: {
                property: 'sequence'
            },
            proxy: {
                type: 'ajax',
                extraParams: {
                    category2Id: 0
                },
                limitParam: 'undefined',
                pageParam: 'undefined',
                url: 'menu/queryalldish',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});