/*
 * File: app/store/IndentDetailStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.store.IndentDetailStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'indentDetailStore',
            proxy: {
                type: 'ajax',
                url: 'indent/queryindentdetail',
                reader: {
                    type: 'json',
                    root: 'details'
                }
            },
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'dishChineseName',
                    type: 'string'
                },
                {
                    name: 'dishEnglishName',
                    type: 'string'
                },
                {
                    name: 'additionalRequirements',
                    type: 'string'
                },
                {
                    name: 'dishPrice',
                    type: 'float'
                },
                {
                    name: 'amount',
                    type: 'int'
                }
            ]
        }, cfg)]);
    }
});