/*
 * File: app/store/IndentRefreshTimeLocalStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.store.IndentRefreshTimeLocalStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'IndentRefreshTimeLocalStore',
            data: [
                {
                    id: '1',
                    name: '1 minute'
                },
                {
                    id: '2',
                    name: '2 minutes'
                },
                {
                    id: '3',
                    name: '3 minutes'
                },
                {
                    id: '4',
                    name: '4 minutes'
                },
                {
                    id: '5',
                    name: '5 minutes'
                }
            ],
            fields: [
                {
                    name: 'name',
                    type: 'string'
                },
                {
                    name: 'id',
                    type: 'int'
                }
            ]
        }, cfg)]);
    }
});