/*
 * File: app/store/LogTypeLocalStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.store.LogTypeLocalStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'LogTypeLocalStore',
            data: [
                {
                    id: '',
                    name: ''
                },
                {
                    id: '1',
                    name: 'ACCOUNT_LOGIN'
                },
                {
                    id: 'ACCOUNT_LOGOUT',
                    name: 'ACCOUNT_LOGOUT'
                },
                {
                    id: 'ACCOUNT_ADD',
                    name: 'ACCOUNT_ADD'
                },
                {
                    id: 'ACCOUNT_MODIFY',
                    name: 'ACCOUNT_MODIFY'
                },
                {
                    id: 'ACCOUNT_DELETE',
                    name: 'ACCOUNT_DELETE'
                },
                {
                    id: 'CATEGORY1_ADD',
                    name: 'CATEGORY1_ADD'
                },
                {
                    id: 'CATEGORY1_MODIFY',
                    name: 'CATEGORY1_MODIFY'
                },
                {
                    id: 'CATEGORY1_DELETE',
                    name: 'CATEGORY1_DELETE'
                },
                {
                    id: 'CATEGORY2_ADD',
                    name: 'CATEGORY2_ADD'
                },
                {
                    id: 'CATEGORY2_MODIFY',
                    name: 'CATEGORY2_MODIFY'
                },
                {
                    id: 'CATEGORY2_DELETE',
                    name: 'CATEGORY2_DELETE'
                },
                {
                    id: 'DISH_ADD',
                    name: 'DISH_ADD'
                },
                {
                    id: 'DISH_MODITY',
                    name: 'DISH_MODITY'
                },
                {
                    id: 'DISH_DELETE',
                    name: 'DISH_DELETE'
                },
                {
                    id: 'CHANGE_CONFIRMCODE',
                    name: 'CHANGE_CONFIRMCODE'
                },
                {
                    id: 'CHANGE_DESK',
                    name: 'CHANGE_DESK'
                },
                {
                    id: 'CHANGE_PRINTER',
                    name: 'CHANGE_PRINTER'
                },
                {
                    id: 'INDENT_PAY',
                    name: 'INDENT_PAY'
                },
                {
                    id: 'INDENT_CANCEL',
                    name: 'INDENT_CANCEL'
                },
                {
                    id: 'INDENTDETAIL_DELETE',
                    name: 'INDENTDETAIL_DELETE'
                },
                {
                    id: 'INDENTDETAIL_CHANGEAMOUNT',
                    name: 'INDENTDETAIL_CHANGEAMOUNT'
                },
                {
                    id: 'INDENTDETAIL_ADDDISH',
                    name: 'INDENTDETAIL_ADDDISH'
                }
            ],
            fields: [
                {
                    name: 'name',
                    type: 'string'
                },
                {
                    name: 'id',
                    type: 'int'
                }
            ]
        }, cfg)]);
    }
});