/*
 * File: app/store/PrinterListStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('digitalmenu.store.PrinterListStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            remoteSort: true,
            storeId: 'PrinterListStore',
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'name',
                    type: 'string'
                },
                {
                    name: 'printerName',
                    type: 'string'
                },
                {
                    name: 'copy',
                    type: 'int'
                },
                {
                    name: 'printStyle',
                    type: 'int'
                }
            ],
            proxy: {
                type: 'ajax',
                limitParam: 'undefined',
                pageParam: 'undefined',
                url: 'common/getprinters',
                reader: {
                    type: 'json',
                    root: 'printers'
                }
            }
        }, cfg)]);
    }
});